# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "whatsapp-chat-button"
client_id = "d8437b8ce81f6502e6eb89d102ebbf7d"
application_url = "https://web-health-developer.myshopify.com/"
embedded = true

[access_scopes]
# Required for reading and writing app metafields
scopes = "write_online_store_pages,read_products"

[auth]
redirect_urls = [
  "https://web-health-developer.myshopify.com//auth/callback",
  "https://web-health-developer.myshopify.com/shopify/callback",
  "https://web-health-developer.myshopify.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "web-health-developer.myshopify.com"
